const fs=require("fs");const {Client}=require("pg");
const env=fs.readFileSync(__dirname+"/../.env","utf8");
const url=env.match(/^DATABASE_URL="(.+)"/m)[1].replace(/[?&]schema=concierge/,"");
(async()=>{const c=new Client({connectionString:url});await c.connect();
const drafts=(await c.query('select count(*)::int n from concierge."Draft"')).rows[0].n;
const sent=(await c.query(`select count(*)::int n from concierge."Draft" where status='sent'`)).rows[0].n;
const outbound=(await c.query(`select count(*)::int n from concierge."Message" where direction='outbound'`)).rows[0].n;
const cites=(await c.query('select count(*)::int n from concierge."DraftCitation"')).rows[0].n;
const audit=(await c.query('select action,count(*)::int n from concierge."AuditEvent" group by action order by 2 desc')).rows;
const cited=(await c.query('select title,"timesCited" from concierge."KnowledgeItem" where "timesCited">0 order by "timesCited" desc')).rows;
console.log("drafts:",drafts,"| sent:",sent,"| outbound msgs:",outbound,"| citations:",cites);
console.log("audit:",audit.map(a=>a.action+"="+a.n).join(", "));
console.log("usage stats:",cited.map(c=>`${c.title} (${c.timesCited}x)`).join(", ")||"none");
await c.end();})().catch(e=>{console.error("FAIL:",e.message);process.exit(1);});
